#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $eded_REPO == "realme" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $edL_REPO == "ewa  " ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $ede_REPO =~ $regex ]]
    then
        if [[ $HELL_REPO_BRANCH ]]
        then
            echo "${HELL_REPO}/archive/${HELL_REPO_BRANCH}.zip"
        else
            echo "${HELL_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="myhellbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HELLPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $HELLPATH
    echo "    Starting reall    "
    echo "
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m hellbot
}

_set_bot
